import type { EntryPreviewRow } from "./entries-types";

export const exampleEntriesMonth = {
  year: 2026,
  month: 9,
};

export const exampleEntryPreviewRows: EntryPreviewRow[] = [
  {
    date: "09/05",
    weekday: "金",
    debit: "普通預金",
    debitType: "asset",
    debitAmount: "5,000",
    credit: "雑収入",
    creditType: "revenue",
    creditAmount: "5,000",
    description: "中古でキーボードを売却",
    partner: "株式会社じゃんぱろ",
    businessRate: "",
    taxCategory: "課税10%",
    businessCategory: "第4種",
  },
  {
    date: "09/10",
    weekday: "木",
    debit: "未払金",
    debitType: "liability",
    debitAmount: "60,000",
    credit: "普通預金",
    creditType: "asset",
    creditAmount: "60,000",
    description: "クレカ代が引き落とされた",
    partner: "VIZAカード株式会社",
    businessRate: "",
    taxCategory: "対象外",
    businessCategory: "",
  },
  {
    date: "09/15",
    weekday: "火",
    debit: "接待交際費",
    debitType: "expense",
    debitAmount: "2,000",
    credit: "現金",
    creditType: "asset",
    creditAmount: "2,000",
    description: "カフェで打ち合わせ",
    partner: "チュターバックス・コーヒー",
    businessRate: "",
    taxCategory: "課税10%",
    businessCategory: "",
  },
  {
    date: "09/20",
    weekday: "日",
    debit: "売上",
    debitType: "revenue",
    debitAmount: "40,000",
    credit: "売掛金",
    creditType: "asset",
    creditAmount: "40,000",
    description: "途中解約を承諾した",
    partner: "ストライク決済代行",
    businessRate: "",
    taxCategory: "課税10%",
    businessCategory: "第5種",
  },
  {
    date: "09/25",
    weekday: "金",
    debit: "旅費交通費",
    debitType: "expense",
    debitAmount: "30,000",
    credit: "未払金",
    creditType: "liability",
    creditAmount: "30,000",
    description: "クレカで新幹線チケット購入",
    partner: "JR南日本",
    businessRate: "",
    taxCategory: "課税10%",
    businessCategory: "",
  },
  {
    date: "09/30",
    weekday: "水",
    debit: "売掛金",
    debitType: "asset",
    debitAmount: "500,000",
    credit: "売上",
    creditType: "revenue",
    creditAmount: "500,000",
    description: "今月分の収益が確定",
    partner: "トヨサ自動車株式会社",
    businessRate: "",
    taxCategory: "課税10%",
    businessCategory: "第5種",
  },
];
