// Generated from resources/gen/bookkeeping_master_data.json. Do not edit directly.
// Regenerate: npm run gen-master-data

import type { EntryAccountVisualType } from "./entries-types";

export type NormalBalanceSide = "debit" | "credit";

export type BalanceSheetSection =
  | "current_asset"
  | "fixed_asset"
  | "deferred_asset"
  | "current_liability"
  | "long_term_liability"
  | "equity"
  | "none";

export type DefaultBookAccount = {
  id: string;
  name: string;
  description: string;
  kana: string;
  normalBalanceSide: NormalBalanceSide;
  accountType: EntryAccountVisualType;
  balanceSheetSection: BalanceSheetSection;
  sortOrder: number;
};

export type DefaultTaxCategory = { id: string; name: string; rate: number };
export type DefaultBusinessCategory = { id: string; name: string };

export const DEFAULT_BOOK_ACCOUNTS: DefaultBookAccount[] = [
  {
    id: "acct_cash",
    name: "現金",
    description: "現金",
    kana: "ｹﾞﾝｷﾝ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 111,
  },
  {
    id: "acct_asset_小口現金",
    name: "小口現金",
    description: "小口現金",
    kana: "ｺｸﾞﾁｹ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 112,
  },
  {
    id: "acct_checking",
    name: "当座預金",
    description: "当座預金",
    kana: "ﾄｳｻﾞﾖ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 121,
  },
  {
    id: "acct_bank",
    name: "普通預金",
    description: "普通預金",
    kana: "ﾌﾂｳﾖｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 131,
  },
  {
    id: "acct_asset_納税準備預金",
    name: "納税準備預金",
    description: "納税準備預金",
    kana: "ﾉｳｾﾞｲ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 139,
  },
  {
    id: "acct_asset_貯蓄預金",
    name: "貯蓄預金",
    description: "貯蓄預金",
    kana: "ﾁｮﾁｸﾖ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 140,
  },
  {
    id: "acct_asset_通知預金",
    name: "通知預金",
    description: "通知預金",
    kana: "ﾂｳﾁﾖｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 141,
  },
  {
    id: "acct_asset_その他の流動性預金",
    name: "その他の流動性預金",
    description: "その他の流動性預金",
    kana: "ｿﾉﾀﾉﾘ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 142,
  },
  {
    id: "acct_time_deposit",
    name: "定期預金",
    description: "定期預金",
    kana: "ﾃｲｷﾖｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 143,
  },
  {
    id: "acct_asset_定期積金",
    name: "定期積金",
    description: "定期積金",
    kana: "ﾃｲｷﾂﾐ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 148,
  },
  {
    id: "acct_asset_その他の固定性預金",
    name: "その他の固定性預金",
    description: "その他の固定性預金",
    kana: "ｿﾉﾀﾉｺ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 149,
  },
  {
    id: "acct_notes_receivable",
    name: "受取手形",
    description: "受取手形",
    kana: "ｳｹﾄﾘﾃ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 150,
  },
  {
    id: "acct_asset_電子記録債権",
    name: "電子記録債権",
    description: "電子記録債権",
    kana: "ﾃﾞﾝｼｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 151,
  },
  {
    id: "acct_receivable",
    name: "売掛金",
    description: "売掛金",
    kana: "ｳﾘｶｹｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 152,
  },
  {
    id: "acct_allowance_bad_debt",
    name: "貸倒引当金",
    description: "貸倒引当金",
    kana: "ｶｼﾀﾞｵ",
    normalBalanceSide: "credit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 159,
  },
  {
    id: "acct_securities",
    name: "有価証券",
    description: "有価証券",
    kana: "ﾕｳｶｼｮ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 161,
  },
  {
    id: "acct_inventory",
    name: "商品",
    description: "商品棚卸",
    kana: "ｼｮｳﾋﾝ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 171,
  },
  {
    id: "acct_asset_製品",
    name: "製品",
    description: "製品",
    kana: "ｾｲﾋﾝ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 175,
  },
  {
    id: "acct_asset_原材料",
    name: "原材料",
    description: "原材料",
    kana: "ｹﾞﾝｻﾞ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 176,
  },
  {
    id: "acct_asset_仕掛品",
    name: "仕掛品",
    description: "仕掛品",
    kana: "ｼｶｶﾘﾋ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 177,
  },
  {
    id: "acct_stored_supplies",
    name: "貯蔵品",
    description: "貯蔵品",
    kana: "ﾁｮｿﾞｳ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 178,
  },
  {
    id: "acct_asset_未収収益",
    name: "未収収益",
    description: "未収収益",
    kana: "ﾐｼｭｳｼ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 180,
  },
  {
    id: "acct_asset_前渡金",
    name: "前渡金",
    description: "前渡金",
    kana: "ﾏｴﾜﾀｼ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 181,
  },
  {
    id: "acct_asset_立替金",
    name: "立替金",
    description: "立替金",
    kana: "ﾀﾃｶｴｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 182,
  },
  {
    id: "acct_asset_短期貸付金",
    name: "短期貸付金",
    description: "短期貸付金",
    kana: "ﾀﾝｷｶｼ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 183,
  },
  {
    id: "acct_accrued_revenue",
    name: "未収入金",
    description: "未収入金",
    kana: "ﾐｼｭｳﾆ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 184,
  },
  {
    id: "acct_prepaid_expense",
    name: "前払費用",
    description: "前払費用（短期）",
    kana: "ﾏｴﾊﾞﾗ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 185,
  },
  {
    id: "acct_asset_繰延税金資産_186",
    name: "繰延税金資産",
    description: "繰延税金資産",
    kana: "ｸﾘﾉﾍﾞ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 186,
  },
  {
    id: "acct_asset_仮払金",
    name: "仮払金",
    description: "仮払金",
    kana: "ｶﾘﾊﾞﾗ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 187,
  },
  {
    id: "acct_asset_その他の流動資産",
    name: "その他の流動資産",
    description: "その他の流動資産",
    kana: "ｿﾉﾀﾉﾘ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 188,
  },
  {
    id: "acct_asset_営業外電子記録債権",
    name: "営業外電子記録債権",
    description: "営業外電子記録債権",
    kana: "ｴｲｷﾞｮ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 189,
  },
  {
    id: "acct_asset_仮払消費税等",
    name: "仮払消費税等",
    description: "仮払消費税等",
    kana: "ｶﾘﾊﾞﾗ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 191,
  },
  {
    id: "acct_asset_未収消費税等",
    name: "未収消費税等",
    description: "未収消費税等",
    kana: "ﾐｼｭｳｼ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 197,
  },
  {
    id: "acct_building",
    name: "建物",
    description: "建物",
    kana: "ﾀﾃﾓﾉ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 211,
  },
  {
    id: "acct_building_facilities",
    name: "建物附属設備",
    description: "建物附属設備",
    kana: "ﾀﾃﾓﾉﾌ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 212,
  },
  {
    id: "acct_asset_構築物",
    name: "構築物",
    description: "構築物",
    kana: "ｺｳﾁｸﾌ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 213,
  },
  {
    id: "acct_machine",
    name: "機械装置",
    description: "機械装置",
    kana: "ｷｶｲｿｳ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 214,
  },
  {
    id: "acct_vehicle",
    name: "車両運搬具",
    description: "車両運搬具",
    kana: "ｼｬﾘｮｳ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 215,
  },
  {
    id: "acct_equipment",
    name: "工具器具備品",
    description: "工具器具備品",
    kana: "ｺｳｸﾞｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 216,
  },
  {
    id: "acct_asset_その他の有形固定資産",
    name: "その他の有形固定資産",
    description: "その他の有形固定資産",
    kana: "ｿﾉﾀﾉﾕ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 218,
  },
  {
    id: "acct_land",
    name: "土地",
    description: "土地",
    kana: "ﾄﾁ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 221,
  },
  {
    id: "acct_asset_建設仮勘定",
    name: "建設仮勘定",
    description: "建設仮勘定",
    kana: "ｹﾝｾﾂｶ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 222,
  },
  {
    id: "acct_asset_減価償却累計額",
    name: "減価償却累計額",
    description: "減価償却累計額",
    kana: "ｹﾞﾝｶｼ",
    normalBalanceSide: "credit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 227,
  },
  {
    id: "acct_asset_減損損失累計額",
    name: "減損損失累計額",
    description: "減損損失累計額",
    kana: "ｹﾞﾝｿﾝ",
    normalBalanceSide: "credit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 229,
  },
  {
    id: "acct_asset_借地権",
    name: "借地権",
    description: "借地権",
    kana: "ｼｬｸﾁｹ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 231,
  },
  {
    id: "acct_asset_電話加入権",
    name: "電話加入権",
    description: "電話加入権",
    kana: "ﾃﾞﾝﾜｶ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 232,
  },
  {
    id: "acct_asset_その他の無形固定資産",
    name: "その他の無形固定資産",
    description: "その他の無形固定資産",
    kana: "ｿﾉﾀﾉﾑ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 233,
  },
  {
    id: "acct_asset_ソフトウエア",
    name: "ソフトウエア",
    description: "ソフトウエア",
    kana: "ｿﾌﾄｳｴ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 234,
  },
  {
    id: "acct_asset_償却累計額",
    name: "償却累計額",
    description: "償却累計額",
    kana: "ｼｮｳｷｬ",
    normalBalanceSide: "credit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 237,
  },
  {
    id: "acct_asset_投資有価証券",
    name: "投資有価証券",
    description: "投資有価証券",
    kana: "ﾄｳｼﾕｳ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 241,
  },
  {
    id: "acct_asset_出資金",
    name: "出資金",
    description: "出資金",
    kana: "ｼｭｯｼｷ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 242,
  },
  {
    id: "acct_asset_長期貸付金",
    name: "長期貸付金",
    description: "長期貸付金",
    kana: "ﾁｮｳｷｶ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 243,
  },
  {
    id: "acct_asset_差入保証金",
    name: "差入保証金",
    description: "差入保証金",
    kana: "ｻｼｲﾚﾎ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 244,
  },
  {
    id: "acct_asset_長期前払費用",
    name: "長期前払費用",
    description: "長期前払費用",
    kana: "ﾁｮｳｷﾏ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 245,
  },
  {
    id: "acct_asset_繰延税金資産_246",
    name: "繰延税金資産",
    description: "繰延税金資産",
    kana: "ｸﾘﾉﾍﾞ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 246,
  },
  {
    id: "acct_asset_その他の投資",
    name: "その他の投資",
    description: "その他の投資",
    kana: "ｿﾉﾀﾉﾄ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 247,
  },
  {
    id: "acct_asset_保険積立金",
    name: "保険積立金",
    description: "保険積立金",
    kana: "ﾎｹﾝﾂﾐ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 248,
  },
  {
    id: "acct_asset_貸倒引当金",
    name: "貸倒引当金",
    description: "貸倒引当金",
    kana: "ｶｼﾀﾞｵ",
    normalBalanceSide: "credit",
    accountType: "asset",
    balanceSheetSection: "fixed_asset",
    sortOrder: 259,
  },
  {
    id: "acct_asset_その他の繰延資産",
    name: "その他の繰延資産",
    description: "その他の繰延資産",
    kana: "ｿﾉﾀﾉｸ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "deferred_asset",
    sortOrder: 291,
  },
  {
    id: "acct_notes_payable",
    name: "支払手形",
    description: "支払手形",
    kana: "ｼﾊﾗｲﾃ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 301,
  },
  {
    id: "acct_liability_電子記録債務",
    name: "電子記録債務",
    description: "電子記録債務",
    kana: "ﾃﾞﾝｼｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 306,
  },
  {
    id: "acct_payable",
    name: "買掛金",
    description: "買掛金",
    kana: "ｶｲｶｹｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 312,
  },
  {
    id: "acct_liability_営業外電子記録債務",
    name: "営業外電子記録債務",
    description: "営業外電子記録債務",
    kana: "ｴｲｷﾞｮ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 320,
  },
  {
    id: "acct_liability_短期借入金",
    name: "短期借入金",
    description: "短期借入金",
    kana: "ﾀﾝｷｶﾘ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 321,
  },
  {
    id: "acct_accrued_expense",
    name: "未払金",
    description: "未払金",
    kana: "ﾐﾊﾞﾗｲ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 322,
  },
  {
    id: "acct_liability_未払費用",
    name: "未払費用",
    description: "未払費用",
    kana: "ﾐﾊﾞﾗｲ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 323,
  },
  {
    id: "acct_advance_received",
    name: "前受金",
    description: "前受金",
    kana: "ﾏｴｳｹｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 324,
  },
  {
    id: "acct_liability_前受収益",
    name: "前受収益",
    description: "前受収益",
    kana: "ﾏｴｳｹｼ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 325,
  },
  {
    id: "acct_deposits_received",
    name: "預り金",
    description: "預り金",
    kana: "ｱｽﾞｶﾘ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 326,
  },
  {
    id: "acct_liability_未払事業税等",
    name: "未払事業税等",
    description: "未払事業税等",
    kana: "ﾐﾊﾞﾗｲ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 327,
  },
  {
    id: "acct_liability_未払法人税等",
    name: "未払法人税等",
    description: "未払法人税等",
    kana: "ﾐﾊﾞﾗｲ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 328,
  },
  {
    id: "acct_liability_繰延税金負債_329",
    name: "繰延税金負債",
    description: "繰延税金負債",
    kana: "ｸﾘﾉﾍﾞ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 329,
  },
  {
    id: "acct_liability_未払配当金",
    name: "未払配当金",
    description: "未払配当金",
    kana: "ﾐﾊﾞﾗｲ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 330,
  },
  {
    id: "acct_liability_仮受金",
    name: "仮受金",
    description: "仮受金",
    kana: "ｶﾘｳｹｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 331,
  },
  {
    id: "acct_liability_その他の流動負債",
    name: "その他の流動負債",
    description: "その他の流動負債",
    kana: "ｿﾉﾀﾉﾘ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 332,
  },
  {
    id: "acct_liability_割引電子記録債権",
    name: "割引電子記録債権",
    description: "割引電子記録債権",
    kana: "ﾜﾘﾋﾞｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 333,
  },
  {
    id: "acct_liability_裏書電子記録債権",
    name: "裏書電子記録債権",
    description: "裏書電子記録債権",
    kana: "ｳﾗｶﾞｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 334,
  },
  {
    id: "acct_liability_仮受消費税等",
    name: "仮受消費税等",
    description: "仮受消費税等",
    kana: "ｶﾘｳｹｼ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 335,
  },
  {
    id: "acct_liability_未払消費税等",
    name: "未払消費税等",
    description: "未払消費税等",
    kana: "ﾐﾊﾞﾗｲ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 336,
  },
  {
    id: "acct_liability_賞与引当金",
    name: "賞与引当金",
    description: "賞与引当金",
    kana: "ｼｮｳﾖﾋ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 337,
  },
  {
    id: "acct_liability_割引手形",
    name: "割引手形",
    description: "割引手形",
    kana: "ﾜﾘﾋﾞｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 338,
  },
  {
    id: "acct_liability_裏書手形",
    name: "裏書手形",
    description: "裏書手形",
    kana: "ｳﾗｶﾞｷ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 339,
  },
  {
    id: "acct_long_term_loan",
    name: "長期借入金",
    description: "長期借入金",
    kana: "ﾁｮｳｷｶ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "long_term_liability",
    sortOrder: 340,
  },
  {
    id: "acct_liability_繰延税金負債_342",
    name: "繰延税金負債",
    description: "繰延税金負債",
    kana: "ｸﾘﾉﾍﾞ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "long_term_liability",
    sortOrder: 342,
  },
  {
    id: "acct_liability_その他の固定負債",
    name: "その他の固定負債",
    description: "その他の固定負債",
    kana: "ｿﾉﾀﾉｺ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "long_term_liability",
    sortOrder: 351,
  },
  {
    id: "acct_liability_退職給付引当金",
    name: "退職給付引当金",
    description: "退職給付引当金",
    kana: "ﾀｲｼｮｸ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "long_term_liability",
    sortOrder: 359,
  },
  {
    id: "acct_liability_その他の引当金",
    name: "その他の引当金",
    description: "その他の引当金",
    kana: "ｿﾉﾀﾉﾋ",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 362,
  },
  {
    id: "acct_equity_資本金",
    name: "資本金",
    description: "資本金",
    kana: "ｼﾎﾝｷﾝ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 411,
  },
  {
    id: "acct_equity_資本準備金",
    name: "資本準備金",
    description: "資本準備金",
    kana: "ｼﾎﾝｼﾞ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 421,
  },
  {
    id: "acct_equity_資本金及び資本準備金減少差益",
    name: "資本金及び資本準備金減少差益",
    description: "資本金及び資本準備金減少差益",
    kana: "ｼﾎﾝｷﾝ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 422,
  },
  {
    id: "acct_equity_自己株式処分差益",
    name: "自己株式処分差益",
    description: "自己株式処分差益",
    kana: "ｼﾞｺｶﾌ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 423,
  },
  {
    id: "acct_equity_利益準備金",
    name: "利益準備金",
    description: "利益準備金",
    kana: "ﾘｴｷｼﾞ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 431,
  },
  {
    id: "acct_equity_別途積立金",
    name: "別途積立金",
    description: "別途積立金",
    kana: "ﾍﾞｯﾄﾂ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 432,
  },
  {
    id: "acct_equity_繰越利益剰余金",
    name: "繰越利益剰余金",
    description: "繰越利益剰余金",
    kana: "ｸﾘｺｼﾘ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 437,
  },
  {
    id: "acct_equity_土地再評価差額金",
    name: "土地再評価差額金",
    description: "土地再評価差額金",
    kana: "ﾄﾁｻｲﾋ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 441,
  },
  {
    id: "acct_equity_その他有価証券評価差額金",
    name: "その他有価証券評価差額金",
    description: "その他有価証券評価差額金",
    kana: "ｿﾉﾀﾕｳ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 442,
  },
  {
    id: "acct_equity_自己株式",
    name: "自己株式",
    description: "自己株式",
    kana: "ｼﾞｺｶﾌ",
    normalBalanceSide: "debit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 443,
  },
  {
    id: "acct_equity_本店",
    name: "本店",
    description: "本店",
    kana: "ﾎﾝﾃﾝ",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 451,
  },
  {
    id: "acct_equity_支店",
    name: "支店",
    description: "支店",
    kana: "ｼﾃﾝ",
    normalBalanceSide: "debit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 452,
  },
  {
    id: "acct_sales",
    name: "売上",
    description: "売上高",
    kana: "ｳﾘｱｹﾞ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 511,
  },
  {
    id: "acct_revenue_非課税売上高",
    name: "非課税売上高",
    description: "非課税売上高",
    kana: "ﾋｶｾﾞｲ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 517,
  },
  {
    id: "acct_revenue_売上値引戻り高",
    name: "売上値引戻り高",
    description: "売上値引戻り高",
    kana: "ｳﾘｱｹﾞ",
    normalBalanceSide: "debit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 521,
  },
  {
    id: "acct_revenue_売上割戻し高",
    name: "売上割戻し高",
    description: "売上割戻し高",
    kana: "ｳﾘｱｹﾞ",
    normalBalanceSide: "debit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 523,
  },
  {
    id: "acct_cost_of_sales_期首商品棚卸高",
    name: "期首商品棚卸高",
    description: "期首商品棚卸高",
    kana: "ｷｼｭｼｮ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 531,
  },
  {
    id: "acct_cost_of_sales_商品仕入高",
    name: "商品仕入高",
    description: "商品仕入高",
    kana: "ｼｮｳﾋﾝ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 541,
  },
  {
    id: "acct_cost_of_sales_非課税仕入高",
    name: "非課税仕入高",
    description: "非課税仕入高",
    kana: "ﾋｶｾﾞｲ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 544,
  },
  {
    id: "acct_cost_of_sales_仕入値引戻し高",
    name: "仕入値引戻し高",
    description: "仕入値引戻し高",
    kana: "ｼｲﾚﾈﾋ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 551,
  },
  {
    id: "acct_cost_of_sales_仕入割戻し高",
    name: "仕入割戻し高",
    description: "仕入割戻し高",
    kana: "ｼｲﾚﾜﾘ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 553,
  },
  {
    id: "acct_cost_of_sales_期末商品棚卸高",
    name: "期末商品棚卸高",
    description: "期末商品棚卸高",
    kana: "ｷﾏﾂｼｮ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 561,
  },
  {
    id: "acct_cost_of_sales_期首製品棚卸高",
    name: "期首製品棚卸高",
    description: "期首製品棚卸高",
    kana: "ｷｼｭｾｲ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 571,
  },
  {
    id: "acct_cost_of_sales_期末製品棚卸高",
    name: "期末製品棚卸高",
    description: "期末製品棚卸高",
    kana: "ｷﾏﾂｾｲ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 591,
  },
  {
    id: "acct_cost_of_sales_期首原材料棚卸高",
    name: "期首原材料棚卸高",
    description: "期首原材料棚卸高",
    kana: "ｷｼｭｹﾞ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 601,
  },
  {
    id: "acct_cost_of_sales_原材料仕入高",
    name: "原材料仕入高",
    description: "原材料仕入高",
    kana: "ｹﾞﾝｻﾞ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 611,
  },
  {
    id: "acct_cost_of_sales_非課税材料仕入",
    name: "非課税材料仕入",
    description: "非課税材料仕入",
    kana: "ﾋｶｾﾞｲ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 616,
  },
  {
    id: "acct_cost_of_sales_原材料仕入値引戻し高",
    name: "原材料仕入値引戻し高",
    description: "原材料仕入値引戻し高",
    kana: "ｹﾞﾝｻﾞ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 621,
  },
  {
    id: "acct_cost_of_sales_材料割戻し高",
    name: "材料割戻し高",
    description: "材料割戻し高",
    kana: "ｻﾞｲﾘｮ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 628,
  },
  {
    id: "acct_cost_of_sales_期末原材料棚卸高",
    name: "期末原材料棚卸高",
    description: "期末原材料棚卸高",
    kana: "ｷﾏﾂｹﾞ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 631,
  },
  {
    id: "acct_cost_of_sales_賃金",
    name: "賃金",
    description: "賃金",
    kana: "ﾁﾝｷﾞﾝ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 641,
  },
  {
    id: "acct_cost_of_sales_賞与",
    name: "賞与",
    description: "賞与",
    kana: "ｼｮｳﾖ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 642,
  },
  {
    id: "acct_cost_of_sales_雑給",
    name: "雑給",
    description: "雑給",
    kana: "ｻﾞｯｷｭ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 643,
  },
  {
    id: "acct_cost_of_sales_退職金",
    name: "退職金",
    description: "退職金",
    kana: "ﾀｲｼｮｸ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 644,
  },
  {
    id: "acct_cost_of_sales_法定福利費",
    name: "法定福利費",
    description: "法定福利費",
    kana: "ﾎｳﾃｲﾌ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 645,
  },
  {
    id: "acct_cost_of_sales_福利厚生費",
    name: "福利厚生費",
    description: "福利厚生費",
    kana: "ﾌｸﾘｺｳ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 646,
  },
  {
    id: "acct_cost_of_sales_その他の労務費",
    name: "その他の労務費",
    description: "その他の労務費",
    kana: "ｿﾉﾀﾉﾛ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 647,
  },
  {
    id: "acct_cost_of_sales_外注加工費",
    name: "外注加工費",
    description: "外注加工費",
    kana: "ｶﾞｲﾁｭ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 651,
  },
  {
    id: "acct_cost_of_sales_その他の製造経費",
    name: "その他の製造経費",
    description: "その他の製造経費",
    kana: "ｿﾉﾀﾉｾ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 661,
  },
  {
    id: "acct_cost_of_sales_動力用光熱費",
    name: "動力用光熱費",
    description: "動力用光熱費",
    kana: "ﾄﾞｳﾘｮ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 671,
  },
  {
    id: "acct_cost_of_sales_賃借料",
    name: "賃借料",
    description: "賃借料",
    kana: "ﾁﾝｼｬｸ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 672,
  },
  {
    id: "acct_cost_of_sales_保険料",
    name: "保険料",
    description: "保険料",
    kana: "ﾎｹﾝﾘｮ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 673,
  },
  {
    id: "acct_cost_of_sales_修繕維持費",
    name: "修繕維持費",
    description: "修繕維持費",
    kana: "ｼｭｳｾﾞ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 674,
  },
  {
    id: "acct_cost_of_sales_減価償却費",
    name: "減価償却費",
    description: "減価償却費",
    kana: "ｹﾞﾝｶｼ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 675,
  },
  {
    id: "acct_cost_of_sales_運賃",
    name: "運賃",
    description: "運賃",
    kana: "ｳﾝﾁﾝ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 676,
  },
  {
    id: "acct_cost_of_sales_消耗品費",
    name: "消耗品費",
    description: "消耗品費",
    kana: "ｼｮｳﾓｳ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 677,
  },
  {
    id: "acct_cost_of_sales_水道光熱費",
    name: "水道光熱費",
    description: "水道光熱費",
    kana: "ｽｲﾄﾞｳ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 678,
  },
  {
    id: "acct_cost_of_sales_交際接待費",
    name: "交際接待費",
    description: "交際接待費",
    kana: "ｺｳｻｲｾ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 679,
  },
  {
    id: "acct_cost_of_sales_旅費交通費",
    name: "旅費交通費",
    description: "旅費交通費",
    kana: "ﾘｮﾋｺｳ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 681,
  },
  {
    id: "acct_cost_of_sales_通信費",
    name: "通信費",
    description: "通信費",
    kana: "ﾂｳｼﾝﾋ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 682,
  },
  {
    id: "acct_cost_of_sales_租税公課",
    name: "租税公課",
    description: "租税公課",
    kana: "ｿｾﾞｲｺ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 683,
  },
  {
    id: "acct_cost_of_sales_リース料",
    name: "リース料",
    description: "リース料",
    kana: "ﾘｰｽﾘｮ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 688,
  },
  {
    id: "acct_cost_of_sales_雑費",
    name: "雑費",
    description: "雑費",
    kana: "ｻﾞｯﾋﾟ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 689,
  },
  {
    id: "acct_cost_of_sales_期首仕掛品棚卸高",
    name: "期首仕掛品棚卸高",
    description: "期首仕掛品棚卸高",
    kana: "ｷｼｭｼｶ",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 691,
  },
  {
    id: "acct_cost_of_sales_期末仕掛品棚卸高",
    name: "期末仕掛品棚卸高",
    description: "期末仕掛品棚卸高",
    kana: "ｷﾏﾂｼｶ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 694,
  },
  {
    id: "acct_cost_of_sales_他勘定振替",
    name: "他勘定振替",
    description: "他勘定振替",
    kana: "ﾀｶﾝｼﾞ",
    normalBalanceSide: "credit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 699,
  },
  {
    id: "acct_expense_役員報酬",
    name: "役員報酬",
    description: "役員報酬",
    kana: "ﾔｸｲﾝﾎ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 711,
  },
  {
    id: "acct_expense_給与手当",
    name: "給与手当",
    description: "給与手当",
    kana: "ｷｭｳﾖﾃ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 712,
  },
  {
    id: "acct_expense_専従者給与",
    name: "専従者給与",
    description: "青色事業専従者へ支払う給与（青色申告決算書 行38）",
    kana: "ｾﾝｼﾞｭｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 714,
  },
  {
    id: "acct_expense_賞与",
    name: "賞与",
    description: "賞与",
    kana: "ｼｮｳﾖ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 713,
  },
  {
    id: "acct_expense_雑給",
    name: "雑給",
    description: "雑給",
    kana: "ｻﾞｯｷｭ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 721,
  },
  {
    id: "acct_expense_退職金",
    name: "退職金",
    description: "退職金",
    kana: "ﾀｲｼｮｸ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 722,
  },
  {
    id: "acct_expense_法定福利費",
    name: "法定福利費",
    description: "法定福利費",
    kana: "ﾎｳﾃｲﾌ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 723,
  },
  {
    id: "acct_welfare",
    name: "福利厚生費",
    description: "福利厚生費",
    kana: "ﾌｸﾘｺｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 724,
  },
  {
    id: "acct_expense_退職給付引当金繰入",
    name: "退職給付引当金繰入",
    description: "退職給付引当金繰入",
    kana: "ﾀｲｼｮｸ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 725,
  },
  {
    id: "acct_travel",
    name: "旅費交通費",
    description: "旅費交通費",
    kana: "ﾘｮﾋｺｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 726,
  },
  {
    id: "acct_communication",
    name: "通信費",
    description: "通信費",
    kana: "ﾂｳｼﾝﾋ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 727,
  },
  {
    id: "acct_expense_販売手数料",
    name: "販売手数料",
    description: "販売手数料",
    kana: "ﾊﾝﾊﾞｲ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 728,
  },
  {
    id: "acct_expense_荷造運賃",
    name: "荷造運賃",
    description: "荷造運賃",
    kana: "ｳﾝﾁﾝ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 731,
  },
  {
    id: "acct_advertising",
    name: "広告宣伝費",
    description: "広告宣伝費",
    kana: "ｺｳｺｸｾ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 732,
  },
  {
    id: "acct_expense_接待交際費",
    name: "接待交際費",
    description: "接待交際費",
    kana: "ｺｳｻｲｾ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 733,
  },
  {
    id: "acct_expense_会議費",
    name: "会議費",
    description: "会議費",
    kana: "ｶｲｷﾞﾋ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 734,
  },
  {
    id: "acct_expense_燃料費",
    name: "燃料費",
    description: "燃料費",
    kana: "ﾈﾝﾘｮｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 735,
  },
  {
    id: "acct_utilities",
    name: "水道光熱費",
    description: "水道光熱費",
    kana: "ｽｲﾄﾞｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 736,
  },
  {
    id: "acct_supplies",
    name: "消耗品費",
    description: "消耗品費",
    kana: "ｼｮｳﾓｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 737,
  },
  {
    id: "acct_taxes_dues",
    name: "租税公課",
    description: "租税公課",
    kana: "ｿｾﾞｲｺ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 738,
  },
  {
    id: "acct_expense_新聞図書費",
    name: "新聞図書費",
    description: "新聞図書費",
    kana: "ｼﾝﾌﾞﾝ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 739,
  },
  {
    id: "acct_expense_支払手数料",
    name: "支払手数料",
    description: "支払手数料",
    kana: "ｼﾊﾗｲﾃ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 741,
  },
  {
    id: "acct_expense_諸会費",
    name: "諸会費",
    description: "諸会費",
    kana: "ｼｮｶｲﾋ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 742,
  },
  {
    id: "acct_expense_寄付金",
    name: "寄付金",
    description: "寄付金",
    kana: "ｷﾌｷﾝ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 743,
  },
  {
    id: "acct_expense_リース料",
    name: "リース料",
    description: "リース料",
    kana: "ﾘｰｽﾘｮ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 744,
  },
  {
    id: "acct_expense_外注費",
    name: "外注費",
    description: "外注費",
    kana: "ｶﾞｲﾁｭ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 745,
  },
  {
    id: "acct_expense_支払報酬",
    name: "支払報酬",
    description: "支払報酬",
    kana: "ｼﾊﾗｲﾎ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 746,
  },
  {
    id: "acct_rent",
    name: "地代家賃",
    description: "地代家賃",
    kana: "ﾁﾀﾞｲﾔ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 747,
  },
  {
    id: "acct_expense_賃借料",
    name: "賃借料",
    description: "賃借料",
    kana: "ﾁﾝｼｬｸ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 751,
  },
  {
    id: "acct_expense_保険料",
    name: "保険料",
    description: "保険料",
    kana: "ﾎｹﾝﾘｮ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 752,
  },
  {
    id: "acct_expense_修繕費",
    name: "修繕費",
    description: "修繕費",
    kana: "ｼｭｳｾﾞ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 753,
  },
  {
    id: "acct_expense_事務用消耗品費",
    name: "事務用消耗品費",
    description: "事務用消耗品費",
    kana: "ｼﾞﾑﾖｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 754,
  },
  {
    id: "acct_expense_その他の一般管理費",
    name: "その他の一般管理費",
    description: "その他の一般管理費",
    kana: "ｿﾉﾀﾉｲ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 755,
  },
  {
    id: "acct_depreciation",
    name: "減価償却費",
    description: "減価償却費",
    kana: "ｹﾞﾝｶｼ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 763,
  },
  {
    id: "acct_expense_貸倒引当金繰入",
    name: "貸倒引当金繰入",
    description: "貸倒引当金繰入",
    kana: "ｶｼﾀﾞｵ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 764,
  },
  {
    id: "acct_expense_賞与引当金繰入",
    name: "賞与引当金繰入",
    description: "賞与引当金繰入",
    kana: "ｼｮｳﾖﾋ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 765,
  },
  {
    id: "acct_expense_貸倒損失",
    name: "貸倒損失",
    description: "貸倒損失",
    kana: "ｶｼﾀﾞｵ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 781,
  },
  {
    id: "acct_misc_expense",
    name: "雑費",
    description: "雑費",
    kana: "ｻﾞｯﾋﾟ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 791,
  },
  {
    id: "acct_revenue_受取利息",
    name: "受取利息",
    description: "受取利息",
    kana: "ｳｹﾄﾘﾘ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 811,
  },
  {
    id: "acct_revenue_受取配当金",
    name: "受取配当金",
    description: "受取配当金",
    kana: "ｳｹﾄﾘﾊ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 812,
  },
  {
    id: "acct_revenue_その他の営業外収益",
    name: "その他の営業外収益",
    description: "その他の営業外収益",
    kana: "ｿﾉﾀﾉｴ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 813,
  },
  {
    id: "acct_revenue_有価証券売却益",
    name: "有価証券売却益",
    description: "有価証券売却益",
    kana: "ﾕｳｶｼｮ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 815,
  },
  {
    id: "acct_revenue_貸倒引当金戻入",
    name: "貸倒引当金戻入",
    description: "貸倒引当金戻入",
    kana: "ｶｼﾀﾞｵ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 816,
  },
  {
    id: "acct_revenue_仕入割引",
    name: "仕入割引",
    description: "仕入割引",
    kana: "ｼｲﾚﾜﾘ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 818,
  },
  {
    id: "acct_misc_income",
    name: "雑収入",
    description: "雑収入",
    kana: "ｻﾞｯｼｭ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 819,
  },
  {
    id: "acct_expense_支払利息",
    name: "支払利息",
    description: "支払利息",
    kana: "ｼﾊﾗｲﾘ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 821,
  },
  {
    id: "acct_expense_その他の営業外費用",
    name: "その他の営業外費用",
    description: "その他の営業外費用",
    kana: "ｿﾉﾀﾉｴ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 822,
  },
  {
    id: "acct_expense_有価証券売却損",
    name: "有価証券売却損",
    description: "有価証券売却損",
    kana: "ﾕｳｶｼｮ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 823,
  },
  {
    id: "acct_expense_手形売却損",
    name: "手形売却損",
    description: "手形売却損",
    kana: "ﾃｶﾞﾀﾊ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 824,
  },
  {
    id: "acct_expense_電子記録債権売却損",
    name: "電子記録債権売却損",
    description: "電子記録債権売却損",
    kana: "ﾃﾞﾝｼｷ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 825,
  },
  {
    id: "acct_expense_売上割引",
    name: "売上割引",
    description: "売上割引",
    kana: "ｳﾘｱｹﾞ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 859,
  },
  {
    id: "acct_expense_雑損失",
    name: "雑損失",
    description: "雑損失",
    kana: "ｻﾞｯｿﾝ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 899,
  },
  {
    id: "acct_revenue_固定資産売却益",
    name: "固定資産売却益",
    description: "固定資産売却益",
    kana: "ｺﾃｲｼｻ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 911,
  },
  {
    id: "acct_revenue_その他の特別利益",
    name: "その他の特別利益",
    description: "その他の特別利益",
    kana: "ｿﾉﾀﾉﾄ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 912,
  },
  {
    id: "acct_revenue_前期損益修正益",
    name: "前期損益修正益",
    description: "前期損益修正益",
    kana: "ｾﾞﾝｷｿ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 915,
  },
  {
    id: "acct_revenue_投資有価証券売却益",
    name: "投資有価証券売却益",
    description: "投資有価証券売却益",
    kana: "ﾄｳｼﾕｳ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 918,
  },
  {
    id: "acct_revenue_償却債権取立益",
    name: "償却債権取立益",
    description: "償却債権取立益",
    kana: "ｼｮｳｷｬ",
    normalBalanceSide: "credit",
    accountType: "revenue",
    balanceSheetSection: "none",
    sortOrder: 919,
  },
  {
    id: "acct_expense_固定資産売却損",
    name: "固定資産売却損",
    description: "固定資産売却損",
    kana: "ｺﾃｲｼｻ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 921,
  },
  {
    id: "acct_expense_その他の特別損失",
    name: "その他の特別損失",
    description: "その他の特別損失",
    kana: "ｿﾉﾀﾉﾄ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 922,
  },
  {
    id: "acct_expense_固定資産除却損",
    name: "固定資産除却損",
    description: "固定資産除却損",
    kana: "ｺﾃｲｼｻ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 924,
  },
  {
    id: "acct_expense_前期損益修正損",
    name: "前期損益修正損",
    description: "前期損益修正損",
    kana: "ｾﾞﾝｷｿ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 925,
  },
  {
    id: "acct_expense_投資有価証券売却損",
    name: "投資有価証券売却損",
    description: "投資有価証券売却損",
    kana: "ﾄｳｼﾕｳ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 927,
  },
  {
    id: "acct_expense_減損損失",
    name: "減損損失",
    description: "減損損失",
    kana: "ｹﾞﾝｿﾝ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 928,
  },
  {
    id: "acct_expense_法人税等",
    name: "法人税等",
    description: "法人税等",
    kana: "ﾎｳｼﾞﾝ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 931,
  },
  {
    id: "acct_expense_法人税等調整額",
    name: "法人税等調整額",
    description: "法人税等調整額",
    kana: "ﾎｳｼﾞﾝ",
    normalBalanceSide: "debit",
    accountType: "expense",
    balanceSheetSection: "none",
    sortOrder: 932,
  },
  {
    id: "acct_asset_諸口",
    name: "諸口",
    description: "諸口",
    kana: "ｼｮｸﾁ",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "none",
    sortOrder: 999,
  },
  {
    id: "acct_other_deposit",
    name: "その他の預金",
    description: "その他の預金",
    kana: "",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 1451,
  },
  {
    id: "acct_inventory_bs",
    name: "棚卸資産",
    description: "棚卸資産",
    kana: "",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 1741,
  },
  {
    id: "acct_advance_payment",
    name: "前払金",
    description: "前払金",
    kana: "",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 1811,
  },
  {
    id: "acct_loan_receivable",
    name: "貸付金",
    description: "貸付金",
    kana: "",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 1831,
  },
  {
    id: "acct_startup_cost",
    name: "開業費",
    description: "開業費",
    kana: "",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "deferred_asset",
    sortOrder: 2921,
  },
  {
    id: "acct_borrowing",
    name: "借入金",
    description: "借入金",
    kana: "",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "long_term_liability",
    sortOrder: 3211,
  },
  {
    id: "acct_proprietor_withdrawal",
    name: "事業主貸",
    description: "事業主貸",
    kana: "",
    normalBalanceSide: "debit",
    accountType: "asset",
    balanceSheetSection: "current_asset",
    sortOrder: 4911,
  },
  {
    id: "acct_proprietor_loan",
    name: "事業主借",
    description: "事業主借",
    kana: "",
    normalBalanceSide: "credit",
    accountType: "liability",
    balanceSheetSection: "current_liability",
    sortOrder: 4921,
  },
  {
    id: "acct_capital",
    name: "元入金",
    description: "元入金",
    kana: "",
    normalBalanceSide: "credit",
    accountType: "equity",
    balanceSheetSection: "equity",
    sortOrder: 4931,
  },
  {
    id: "acct_purchases",
    name: "仕入",
    description: "仕入",
    kana: "",
    normalBalanceSide: "debit",
    accountType: "cost_of_sales",
    balanceSheetSection: "none",
    sortOrder: 5411,
  },
];

export const DEFAULT_TAX_CATEGORIES: DefaultTaxCategory[] = [
  { id: "tax_10", name: "課税 10%", rate: 1000 },
  { id: "tax_8", name: "軽減税率 8%", rate: 800 },
  { id: "tax_exempt", name: "免税", rate: 0 },
  { id: "tax_non_taxable", name: "非課税", rate: 0 },
  { id: "tax_out_of_scope", name: "対象外", rate: 0 },
];

export const DEFAULT_BUSINESS_CATEGORIES: DefaultBusinessCategory[] = [
  { id: "biz_1", name: "第1種（卸売業）" },
  { id: "biz_2", name: "第2種（小売業等）" },
  { id: "biz_3", name: "第3種（製造業等）" },
  { id: "biz_4", name: "第4種（その他）" },
  { id: "biz_5", name: "第5種（サービス業等）" },
  { id: "biz_6", name: "第6種（不動産業）" },
  { id: "biz_none", name: "対象外" },
];
