import type { FsBsRow } from "../fs-data";

export const FINANCIAL_STATEMENTS_EXAMPLE_FP_NAME = "サンプル期間 (2026年度)";

export const FINANCIAL_STATEMENTS_EXAMPLE_AMOUNTS: Record<
  number,
  number | null
> = {
  1: 4500000,
  2: null,
  3: null,
  4: 0,
  5: null,
  6: 0,
  7: 4500000,
  8: null,
  9: null,
  10: 60000,
  11: 120000,
  12: 60000,
  13: null,
  14: 30000,
  15: null,
  16: null,
  17: 100000,
  18: 80000,
  19: null,
  20: null,
  21: null,
  22: null,
  23: 500000,
  24: null,
  25: 20000,
  26: null,
  27: null,
  28: null,
  29: null,
  30: null,
  31: 30000,
  32: 950000,
  33: 3550000,
  34: null,
  35: null,
  36: null,
  37: 0,
  38: null,
  39: null,
  40: null,
  41: null,
  42: 0,
  43: 3550000,
};

const PROFIT = 3550000;
const OPENING_ASSETS_TOTAL = 50000 + 1500000 + 200000;
const ASSETS_TOTAL = 80000 + 2800000 + 460000 + 136550 + 800000;
const OPENING_LIABS_TOTAL = 1750000;
const LIABS_AND_EQUITY_TOTAL_DISPLAY = 1750000 + PROFIT;

export const FINANCIAL_STATEMENTS_EXAMPLE_BS_ROWS: FsBsRow[] = [
  {
    assetLabel: "現金",
    assetOpening: 50000,
    assetClosing: 80000,
    liabilityLabel: "支払手形",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "当座預金",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "買掛金",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "定期預金",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "借入金",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "その他の預金",
    assetOpening: 1500000,
    assetClosing: 2800000,
    liabilityLabel: "未払金",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "受取手形",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "前受金",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "売掛金",
    assetOpening: null,
    assetClosing: 460000,
    liabilityLabel: "預り金",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "有価証券",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "棚卸資産",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "前払金",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "貸付金",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "建物",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "建物附属設備",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "機械装置",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "車両運搬具",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "貸倒引当金",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "工具器具備品",
    assetOpening: 200000,
    assetClosing: 136550,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "土地",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "事業主借",
    liabilityOpening: null,
    liabilityClosing: null,
  },
  {
    assetLabel: "",
    assetOpening: null,
    assetClosing: null,
    liabilityLabel: "元入金",
    liabilityOpening: 1750000,
    liabilityClosing: 1750000,
  },
  {
    assetLabel: "事業主貸",
    assetOpening: null,
    assetClosing: 800000,
    liabilityLabel: "青色申告特別控除前の所得金額",
    liabilityOpening: null,
    liabilityClosing: PROFIT,
  },
  {
    assetLabel: "合計",
    assetOpening: OPENING_ASSETS_TOTAL,
    assetClosing: ASSETS_TOTAL,
    liabilityLabel: "合計",
    liabilityOpening: OPENING_LIABS_TOTAL,
    liabilityClosing: LIABS_AND_EQUITY_TOTAL_DISPLAY,
  },
];
